### ISSUE TITLE
c-blox logo

### ISSUE THREAD

**Issue by helenol** [ethz-asl/cblox#1]
![c_blox_new_small](https://user-images.githubusercontent.com/5616392/43275997-ab8f3af2-9103-11e8-89d6-36759ad1c3eb.png)

**Comment by ZacharyTaylor** [comment]
This is the opposite of an issue

**Comment by marco-tranzatto** [comment]
Can I have a sticker of the proper logo please? :heart_eyes:

**Comment by alexmillane** [comment]
Half size

![cblox_logo_half](https://user-images.githubusercontent.com/671701/55418812-b94de280-5573-11e9-9574-c83660fe3354.png)

**Comment by alexmillane** [comment]
![kitti_rviz_trim](https://user-images.githubusercontent.com/671701/55502193-50866900-564c-11e9-999e-b78bf71dd3d4.png)

**Comment by alexmillane** [comment]
![kitti](https://user-images.githubusercontent.com/671701/55502987-04d4bf00-564e-11e9-964c-11e7ba7ea754.gif)
