### ISSUE TITLE
Using c-blox / voxblox with multiple sensors / robots

### ISSUE THREAD

**Issue by madratman** [ethz-asl/cblox#13]
I'd love to get your thoughts on what would need to be changed / done to enable multi-robot / multi sensor mapping?
The ugliest and easiest hack is remapping tf's and pointclouds on the same topic, but well, that's _pretty_ ugly. 
If do this ugly hack, do I need to add "locks" to the integrator to avoid any potential race conditions? Or another ugly hack I can do is ensure the timestamps of different pointclouds from different robot / sensors are always slightly off each other. 

Edit - actually I think I was wrong about any race conditions if it's just a callback. I guess then a potential issue would instead be of involuntary dropping of input messages.

**Comment by alexmillane** [comment]
Hmm interesting question. My inclination would be towards starting a submap server _per robot_, such that each builds its own submap collection. If you want a combined map I would write a server which subscribes to the published serialized submaps and combines them (there's currently an open pull-request for publishing serialized submaps #10 ). This would rely on the robots being localized in a common reference frame though...

The question of multiple sensors on one robot is a far easier problem. So long as you use the tf tree as the transformation source and all the relevant (sensor-to-sensor) transforms are there, I don't see a problem with things working as they are now.

**Comment by madratman** [comment]
Thanks a lot @alexmillane! submaps makes sense, I somehow forgot to mention them in my first comment. oops. yeah, I wasn't able to find how to fuse them on demand / over a timer callback. that PR looks awesome and waiting for it to merge 
I've been hacking something on the lines of what you said, and will update soon.

**Comment by alexmillane** [comment]
@madratman I hope you had some success in using the system. I'll close this issue for now. Feel free to reopen it if you have further questions.
