### ISSUE TITLE
Running cblox on live data

### ISSUE THREAD

**Issue by realdealneil** [ethz-asl/cblox#20]
I have gotten the example to work on kitti data, and now I'm interested in getting it working on some simulated data.  My simulated robot is using SLAM to estimate it's pose, which is being output to the /map frame.  Does cblox assume the ability to do a tf lookup relative to the /world frame?  Can I change what frame it uses as the base frame?  

I simply modified the run_kitti.launch file and changed the points remap argument.  I think the pointcloud are being received, but I'm getting the following error:

"Input pointcloud queue getting too long! Dropping some pointclouds. Either unable to look up transform timestamps or the processing is taking too long."

**Comment by realdealneil** [comment]
I found the parameter to set the world frame and added it to my launch file (world_frame="map").  Now, it looks like the frames are being integrated, but nothing is being published on the submap or trajectory topics.  Is there something more I need to do to get this running on live data?

**Comment by realdealneil** [comment]
Ok, I got it figured out.  It actually was publishing the data, but I was adding the wrong rviz elements for visualizing.  It is working just fine now that I changed the world frame id.  Very cool!  Nice work on this!

**Comment by alexmillane** [comment]
Thanks for the interest in this :). Glad to hear you got things working.

**Comment by virajawate** [comment]
I have the kitti data in modules, how can i integrate it or better if i got the kitti in one whole from somewhere.
