### ISSUE TITLE
cmake bug in submap.cpp

### ISSUE THREAD

**Issue by holyly** [ethz-asl/cblox#42]
I got many errors in submap.cpp!!!!!

/home/h/Documents/project/voxgraph/catkin_ws/src/cblox/cblox/src/core/tsdf_submap.cpp:62:66: error: invalid conversion from ‘std::istream* {aka std::basic_istream<char>*}’ to ‘std::fstream* {aka std::basic_fstream<char>*}’ [-fpermissive]
                                               tmp_byte_offset_ptr)) {
                                                                  ^
/home/h/Documents/project/voxgraph/catkin_ws/src/cblox/cblox/src/core/tsdf_submap.cpp:62:66: error: cannot convert ‘uint64_t* {aka long unsigned int*}’ to ‘uint32_t* {aka unsigned int*}’ for argument ‘3’ to ‘bool voxblox::utils::readProtoMsgFromStream(std::fstream*, google::protobuf::Message*, uint32_t*)’
/home/h/Documents/project/voxgraph/catkin_ws/src/cblox/cblox/src/core/tsdf_submap.cpp:88:30: error: no matching function for call to ‘LoadBlocksFromStream(google::protobuf::uint32, voxblox::Layer<voxblox::TsdfVoxel>::BlockMergingStrategy, std::istream*&, voxblox::Layer<voxblox::TsdfVoxel>*, uint64_t*&)’
           tmp_byte_offset_ptr)) {
                              ^
In file included from /home/h/Documents/project/coorate/catkin_ws/src/voxblox_multi_agent/voxblox/include/voxblox/io/layer_io.h:76:0,
                 from /home/h/Documents/project/coorate/catkin_ws/src/voxblox_multi_agent/voxblox/include/voxblox/core/esdf_map.h:14,
                 from /home/h/Documents/project/voxgraph/catkin_ws/src/cblox/cblox/include/cblox/core/common.h:13,
                 from /home/h/Documents/project/voxgraph/catkin_ws/src/cblox/cblox/include/cblox/core/tsdf_submap.h:12,
                 from /home/h/Documents/project/voxgraph/catkin_ws/src/cblox/cblox/src/core/tsdf_submap.cpp:1:
/home/h/Documents/project/coorate/catkin_ws/src/voxblox_multi_agent/voxblox/include/voxblox/io/layer_io_inl.h:104:6: note: candidate: template<class VoxelType> bool voxblox::io::LoadBlocksFromStream(size_t, typename voxblox::Layer<VoxelType>::BlockMergingStrategy, std::fstream*, voxblox::Layer<VoxelType>*, uint32_t*)
 bool LoadBlocksFromStream(
      ^~~~~~~~~~~~~~~~~~~~
/home/h/Documents/project/coorate/catkin_ws/src/voxblox_multi_agent/voxblox/include/voxblox/io/layer_io_inl.h:104:6: note:   template argument deduction/substitution failed:
/home/h/Documents/project/voxgraph/catkin_ws/src/cblox/cblox/src/core/tsdf_submap.cpp:88:30: note:   cannot convert ‘proto_file_ptr’ (type ‘std::istream* {aka std::basic_istream<char>*}’) to type ‘std::fstream* {aka std::basic_fstream<char>*}’
           tmp_byte_offset_ptr)) {
                              ^
/home/h/Documents/project/voxgraph/catkin_ws/src/cblox/cblox/src/core/tsdf_esdf_submap.cpp: In static member function ‘static cblox::TsdfEsdfSubmap::Ptr cblox::TsdfEsdfSubmap::LoadFromStream(const cblox::TsdfEsdfSubmap::Config&, std::istream*, uint64_t*)’:
/home/h/Documents/project/voxgraph/catkin_ws/src/cblox/cblox/src/core/tsdf_esdf_submap.cpp:59:66: error: invalid conversion from ‘std::istream* {aka std::basic_istream<char>*}’ to ‘std::fstream* {aka std::basic_fstream<char>*}’ [-fpermissive]
                                               tmp_byte_offset_ptr)) {
                                                                  ^
/home/h/Documents/project/voxgraph/catkin_ws/src/cblox/cblox/src/core/tsdf_esdf_submap.cpp:59:66: error: cannot convert ‘uint64_t* {aka long unsigned int*}’ to ‘uint32_t* {aka unsigned int*}’ for argument ‘3’ to ‘bool voxblox::utils::readProtoMsgFromStream(std::fstream*, google::protobuf::Message*, uint32_t*)’
/home/h/Documents/project/voxgraph/catkin_ws/src/cblox/cblox/src/core/tsdf_esdf_submap.cpp:85:30: error: no matching function for call to ‘LoadBlocksFromStream(google::protobuf::uint32, voxblox::Layer<voxblox::TsdfVoxel>::BlockMergingStrategy, std::istream*&, voxblox::Layer<voxblox::TsdfVoxel>*, uint64_t*&)’
           tmp_byte_offset_ptr)) {
                              ^
In file included from /home/h/Documents/project/coorate/catkin_ws/src/voxblox_multi_agent/voxblox/include/voxblox/io/layer_io.h:76:0,
                 from /home/h/Documents/project/coorate/catkin_ws/src/voxblox_multi_agent/voxblox/include/voxblox/core/esdf_map.h:14,
                 from /home/h/Documents/project/voxgraph/catkin_ws/src/cblox/cblox/include/cblox/core/common.h:13,
                 from /home/h/Documents/project/voxgraph/catkin_ws/src/cblox/cblox/include/cblox/core/tsdf_submap.h:12,
                 from /home/h/Documents/project/voxgraph/catkin_ws/src/cblox/cblox/include/cblox/core/tsdf_esdf_submap.h:8,
                 from /home/h/Documents/project/voxgraph/catkin_ws/src/cblox/cblox/src/core/tsdf_esdf_submap.cpp:1:
/home/h/Documents/project/coorate/catkin_ws/src/voxblox_multi_agent/voxblox/include/voxblox/io/layer_io_inl.h:104:6: note: candidate: template<class VoxelType> bool voxblox::io::LoadBlocksFromStream(size_t, typename voxblox::Layer<VoxelType>::BlockMergingStrategy, std::fstream*, voxblox::Layer<VoxelType>*, uint32_t*)
 bool LoadBlocksFromStream(
      ^~~~~~~~~~~~~~~~~~~~
/home/h/Documents/project/coorate/catkin_ws/src/voxblox_multi_agent/voxblox/include/voxblox/io/layer_io_inl.h:104:6: note:   template argument deduction/substitution failed:
/home/h/Documents/project/voxgraph/catkin_ws/src/cblox/cblox/src/core/tsdf_esdf_submap.cpp:85:30: note:   cannot convert ‘proto_file_ptr’ (type ‘std::istream* {aka std::basic_istream<char>*}’) to type ‘std::fstream* {aka std::basic_fstream<char>*}’
           tmp_byte_offset_ptr)) {
                              ^
/home/h/Documents/project/voxgraph/catkin_ws/src/cblox/cblox/src/core/tsdf_esdf_submap.cpp:100:30: error: no matching function for call to ‘LoadBlocksFromStream(google::protobuf::uint32, voxblox::Layer<voxblox::EsdfVoxel>::BlockMergingStrategy, std::istream*&, voxblox::Layer<voxblox::EsdfVoxel>*, uint64_t*&)’
           tmp_byte_offset_ptr)) {
                              ^

**Comment by holyly** [comment]
I solved the problem by recompiling voxblox, so I close this problem.

**Comment by alexmillane** [comment]
Hi. It looks like you have an old version of voxblox. Please pull the latest version.
