### ISSUE TITLE
catkin build error: ‘getMeshIntegratorConfigFromRosParam’ is not a member of ‘voxblox’

### ISSUE THREAD

**Issue by Natalie-ZG** [ethz-asl/cblox#5]
catkin build get error: 
error: ‘getMeshIntegratorConfigFromRosParam’ is not a member of ‘voxblox’
           voxblox::getMeshIntegratorConfigFromRosParam(nh_private)) {}

I search the function in voxblox and find nothing. Is there any version matching request for voxblox and c-blox?

**Comment by alexmillane** [comment]
Ah damn, I forgot I have an open PR on voxblox with this function. I will try to get this merged today. For the time being you will have to check out [this branch](https://github.com/ethz-asl/voxblox/tree/feature/mesh_integrator_config_params) on voxblox.

Thanks for drawing this to my attention.

**Comment by alexmillane** [comment]
This should be fixed now!
